version: 0.1
   
phases:
  install:
    commands:
      - echo "******** Installing Hugo ********"
      - curl -L https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-32bit.tar.gz | tar xz 
      - mv hugo_0.18.1_linux_386/hugo_0.18.1_linux_386 ./hugo
      - echo "******** Done ********"
  build:
    commands:
      - echo "******** Building Site ********"
      - ./hugo 
      - echo "******** Done ********"
  post_build:
    commands:
      - echo "******** Uploading to S3 ********"
      - aws s3 sync public/ s3://yas3s.com --delete --acl public-read
      - echo "******** Done ********"

artifacts:
  files:
    - public/**/*
